Repository xorgram/xor, pull requests merged in 2022-04, with the labels that each got.

#125 chore!: remove bin
  bin/env.js
  bin/index.js
  package-lock.json
  package.json
  scripts/start.sh
  src/env.ts
  src/index.ts
  src/module_manager.ts
Labels: chore, BREAKING CHANGE

#129 chore(scripts): delete `dist` if existing
  scripts/start.ps1
  scripts/start.sh
Labels: chore

#128 chore: add `scripts` to `.npmignore`
  .npmignore
Labels: chore

#130 fix: external module spec
  src/module_manager.ts
Labels: fix

#162 chore(style): sort imports
  .prettierrc
  package-lock.json
  package.json
  src/index.ts
  src/module_manager.ts
  src/modules/admin/helpers.ts
  src/modules/admin/index.ts
  src/modules/files/index.ts
  src/modules/util/helpers.ts
  src/modules/util/index.ts
Labels: style, chore

#152 feat: initialize database
  package-lock.json
  package.json
  src/db.ts
  src/env.ts
Labels: feat
