Repository xorgram/xor, pull requests merged in 2022-03, with the labels that each got.

#62 feat: add admin module
  package-lock.json
  package.json
  src/modules/admin/helpers.ts
  src/modules/admin/index.ts
Labels: feat

#86 feat: avail `methods` in `eval` and update help
  src/modules/util/index.ts
Labels: feat

#92 ci: add the `publish` job from methods
  .github/workflows/ci.yml
Labels: ci

#93 fix: the response style on `unpin`
  src/modules/admin/index.ts
Labels: fix

#94 ci: simplify, remove not required args and duplicates
  .github/workflows/ci.yml
Labels: ci

#95 feat: `admin.add`
  package-lock.json
  package.json
  src/modules/admin/index.ts
Labels: feat

#121 ci: cache npm modules for better performance
  .github/workflows/ci.yml
Labels: ci

#122 ci: attach package archive to release
  .github/workflows/ci.yml
Labels: ci

#123 ci: clean and update
  .github/workflows/ci.yml
Labels: ci
